[package]
name = "hypeerlog"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
criterion = { version = "0.6" }
rand = "0.9.2"

[[bench]]
harness = false
name = "performance"

[profile.release]
strip = "symbols"
